# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-chat-md-export" do
  desc "CLI tool to convert ChatGPT and Claude chat history to Markdown"
  homepage "https://github.com/sugurutakahashi-1234/ai-chat-md-export"
  version "0.8.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-chat-md-export"

  on_macos do
    on_intel do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v0.8.3/ai-chat-md-export-darwin-amd64.tar.gz"
      sha256 "4a49e5ae6cdf85ea504d195bfbb60de30d3b53339a0a46bebac6361876d63357"
    end
    on_arm do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v0.8.3/ai-chat-md-export-darwin-arm64.tar.gz"
      sha256 "7f6bb0282ddc49cb63fa4284851ab4fa2e170ea58710f25686826dfa84a71e65"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v0.8.3/ai-chat-md-export-linux-amd64.tar.gz"
      sha256 "f86a4432886322e435f32d7e6f4068c0773f00e963a3e95116f505701adda305"
    end
    on_arm do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v0.8.3/ai-chat-md-export-linux-arm64.tar.gz"
      sha256 "6140926ee760619c3818b3c0910cf70fd78f034c4e957b48eeb3b3eb108b4ee0"
    end
  end

  conflicts_with formula: [
      "ai-chat-md-export",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai-chat-md-export"]
    end
  end

  # No zap stanza required
end
