# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-chat-md-export" do
  desc "CLI tool to convert ChatGPT and Claude chat history to Markdown"
  homepage "https://github.com/sugurutakahashi-1234/ai-chat-md-export"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-chat-md-export"

  on_macos do
    on_intel do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v1.0.1/ai-chat-md-export-darwin-amd64.tar.gz"
      sha256 "feda52f5c0b525272d174d48834cc90752cfd031fb7cccaf31386406aa61b185"
    end
    on_arm do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v1.0.1/ai-chat-md-export-darwin-arm64.tar.gz"
      sha256 "3d3a13adceb5bf97f3cf6c3678621bc4d6e673e92d6d5b67c9e3101364c50331"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v1.0.1/ai-chat-md-export-linux-amd64.tar.gz"
      sha256 "3376c7bda76087e3c0ed58d8b9bc825ba091ef818ad24050696ed60acbbfe326"
    end
    on_arm do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v1.0.1/ai-chat-md-export-linux-arm64.tar.gz"
      sha256 "f40514f4b4aa6833f1867eaaa36917c05a815e96143207979a6e7fdbaf461414"
    end
  end

  conflicts_with formula: [
      "ai-chat-md-export",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai-chat-md-export"]
    end
  end

  # No zap stanza required
end
