# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-chat-md-export" do
  desc "CLI tool to convert ChatGPT and Claude chat history to Markdown"
  homepage "https://github.com/sugurutakahashi-1234/ai-chat-md-export"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-chat-md-export"

  on_macos do
    on_intel do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v1.0.3/ai-chat-md-export-darwin-amd64.tar.gz"
      sha256 "cb1b4e235f951504136d17f341a8575b2edc5e20359ef6f0ec468774cc57afaf"
    end
    on_arm do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v1.0.3/ai-chat-md-export-darwin-arm64.tar.gz"
      sha256 "e194fd98a3ea755be1e2c08a220efb800bcd5a0394206e3f98fb9b6f0da1a241"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v1.0.3/ai-chat-md-export-linux-amd64.tar.gz"
      sha256 "339a1da3237bba9073a5e61000f37558786161f902cb8305432b6d8bbaf55340"
    end
    on_arm do
      url "https://github.com/sugurutakahashi-1234/ai-chat-md-export/releases/download/v1.0.3/ai-chat-md-export-linux-arm64.tar.gz"
      sha256 "70a44c7ac525b2958ec22ee4285dd5ca9270675bc9ac4aa57972365bdadabc4d"
    end
  end

  conflicts_with formula: [
      "ai-chat-md-export",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai-chat-md-export"]
    end
  end

  # No zap stanza required
end
